In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from sklearn.model_selection import train_test_split,cross_val_score , ShuffleSplit , GridSearchCV
from sklearn.linear_model import LinearRegression , Lasso
from sklearn.tree import DecisionTreeRegressor

In [9]:
Bengalore= pd.read_csv("Bangalore.csv")
Bengalore.head(3)

Price  Area                         Location  No. of Bedrooms  Resale  \
0  30000000  3340                 JP Nagar Phase 1                4       0   
1   7888000  1045       Dasarahalli on Tumkur Road                2       0   
2   4866000  1179  Kannur on Thanisandra Main Road                2       0   

   MaintenanceStaff  Gymnasium  SwimmingPool  LandscapedGardens  JoggingTrack  \
0                 1          1             1                  1             1   
1                 0          1             1                  1             1   
2                 0          1             1                  1             1   

   ...  LiftAvailable  BED  VaastuCompliant  Microwave  GolfCourse  TV  \
0  ...              1    0                0          0           0   0   
1  ...              1    0                1          0           0   0   
2  ...              1    0                0          0           0   0   

   DiningTable  Sofa  Wardrobe  Refrigerator  
0            0     0         0             0  
1            0     0         0             0  
2            0     0         0             0  

[3 rows x 40 columns]

In [10]:
Bengalore.columns

Index(['Price', 'Area', 'Location', 'No. of Bedrooms', 'Resale',
       'MaintenanceStaff', 'Gymnasium', 'SwimmingPool', 'LandscapedGardens',
       'JoggingTrack', 'RainWaterHarvesting', 'IndoorGames', 'ShoppingMall',
       'Intercom', 'SportsFacility', 'ATM', 'ClubHouse', 'School',
       '24X7Security', 'PowerBackup', 'CarParking', 'StaffQuarter',
       'Cafeteria', 'MultipurposeRoom', 'Hospital', 'WashingMachine',
       'Gasconnection', 'AC', 'Wifi', 'Children'splayarea', 'LiftAvailable',
       'BED', 'VaastuCompliant', 'Microwave', 'GolfCourse', 'TV',
       'DiningTable', 'Sofa', 'Wardrobe', 'Refrigerator'],
      dtype='object')

In [11]:
Bengalore.drop(columns=['Resale','MaintenanceStaff', 'Gymnasium', 'SwimmingPool', 'LandscapedGardens',
       'JoggingTrack', 'RainWaterHarvesting', 'IndoorGames', 'ShoppingMall',
       'Intercom', 'SportsFacility', 'ATM', 'ClubHouse', 'School',
       '24X7Security', 'PowerBackup', 'CarParking', 'StaffQuarter',
       'Cafeteria', 'MultipurposeRoom', 'Hospital', 'WashingMachine',
       'Gasconnection', 'AC', 'Wifi', "Children'splayarea", 'LiftAvailable','BED', 
        'VaastuCompliant', 'Microwave', 'GolfCourse', 'TV','DiningTable', 
        'Sofa', 'Wardrobe', 'Refrigerator'],inplace = True)

In [12]:
Bengalore.head()

Price  Area                         Location  No. of Bedrooms
0  30000000  3340                 JP Nagar Phase 1                4
1   7888000  1045       Dasarahalli on Tumkur Road                2
2   4866000  1179  Kannur on Thanisandra Main Road                2
3   8358000  1675                     Doddanekundi                3
4   6845000  1670                          Kengeri                3

In [14]:
for col in Bengalore.columns:
    print(f'{col}  :- {Bengalore[col].unique()}')

Price  :- [30000000  7888000  4866000 ...  6251000  7373000  4985000]
Area  :- [3340 1045 1179 ... 2204  873 2064]
Location  :- ['JP Nagar Phase 1' 'Dasarahalli on Tumkur Road'
 'Kannur on Thanisandra Main Road' 'Doddanekundi' 'Kengeri' 'Horamavu'
 'Thanisandra' 'Ramamurthy Nagar' 'Whitefield Hope Farm Junction'
 'Electronic City Phase 1' 'Yelahanka' 'Anjanapura' 'Jalahalli'
 'Kasavanahalli' 'Bommasandra' 'Bellandur' 'RR Nagar' 'Begur' 'Hosa Road'
 'Sahakar Nagar' 'Kadugodi' 'Jakkur' 'Jigani' 'Krishnarajapura'
 'Brookefield' 'Banashankari' 'Nelamangala' 'Attibele' 'Banaswadi'
 'Kodigehalli' 'ITPL' 'Uttarahalli Hobli'
 'Chikkagubbi on Hennur Main Road' 'Varthur' 'Vidyaranyapura'
 'Electronic City Phase 2' 'J. P. Nagar' 'K. Chudahalli' 'Narayanaghatta'
 'Anekal City' 'Sarjapur' 'Koramangala' 'Hebbal' 'Budigere Cross'
 'Bommanahalli' 'Electronics City' 'Chikkalasandra' 'Kogilu'
 'Nayandahalli' 'Bilekahalli' 'Muneshwara Nagar' 'Junnasandra'
 'Narayanapura on Hennur Main Road' 'Kothanur' 'K

In [15]:
Bengalore.dtypes

Price               int64
Area                int64
Location           object
No. of Bedrooms     int64
dtype: object

In [16]:
Bengalore["No. of Bedrooms"].unique()

array([4, 2, 3, 1, 5, 6, 7], dtype=int64)

In [17]:
Bengalore["No. of Bedrooms"].value_counts()

3    2799
2    2750
4     402
1     230
5      22
6       2
7       2
Name: No. of Bedrooms, dtype: int64

In [18]:
for index , i in enumerate(Bengalore["No. of Bedrooms"]):
    if i==9:
        print(index)

In [19]:
Bengalore.head()

Price  Area                         Location  No. of Bedrooms
0  30000000  3340                 JP Nagar Phase 1                4
1   7888000  1045       Dasarahalli on Tumkur Road                2
2   4866000  1179  Kannur on Thanisandra Main Road                2
3   8358000  1675                     Doddanekundi                3
4   6845000  1670                          Kengeri                3

In [20]:
Bengalore["Location"].unique()

array(['JP Nagar Phase 1', 'Dasarahalli on Tumkur Road',
       'Kannur on Thanisandra Main Road', 'Doddanekundi', 'Kengeri',
       'Horamavu', 'Thanisandra', 'Ramamurthy Nagar',
       'Whitefield Hope Farm Junction', 'Electronic City Phase 1',
       'Yelahanka', 'Anjanapura', 'Jalahalli', 'Kasavanahalli',
       'Bommasandra', 'Bellandur', 'RR Nagar', 'Begur', 'Hosa Road',
       'Sahakar Nagar', 'Kadugodi', 'Jakkur', 'Jigani', 'Krishnarajapura',
       'Brookefield', 'Banashankari', 'Nelamangala', 'Attibele',
       'Banaswadi', 'Kodigehalli', 'ITPL', 'Uttarahalli Hobli',
       'Chikkagubbi on Hennur Main Road', 'Varthur', 'Vidyaranyapura',
       'Electronic City Phase 2', 'J. P. Nagar', 'K. Chudahalli',
       'Narayanaghatta', 'Anekal City', 'Sarjapur', 'Koramangala',
       'Hebbal', 'Budigere Cross', 'Bommanahalli', 'Electronics City',
       'Chikkalasandra', 'Kogilu', 'Nayandahalli', 'Bilekahalli',
       'Muneshwara Nagar', 'Junnasandra',
       'Narayanapura on Hennur Ma

In [21]:
len(Bengalore["Location"].unique())

302

In [22]:
(Bengalore["Location"].value_counts())

Electronic City Phase 2      232
RR Nagar                     217
Begur                        186
Varthur                      168
Kumaraswamy Layout           154
                            ... 
Ullal Uppanagar                1
Bengaluru Kanakapura Road      1
Infantry Road                  1
Sidedahalli                    1
Vijaya Bank Layout             1
Name: Location, Length: 302, dtype: int64

In [23]:
for i in Bengalore["Location"]:
    print(i)

JP Nagar Phase 1
Dasarahalli on Tumkur Road
Kannur on Thanisandra Main Road
Doddanekundi
Kengeri
Horamavu
Thanisandra
Ramamurthy Nagar
Whitefield Hope Farm Junction
Electronic City Phase 1
Yelahanka
Anjanapura
Jalahalli
Kasavanahalli
Whitefield Hope Farm Junction
Bommasandra
Bellandur
RR Nagar
JP Nagar Phase 1
Dasarahalli on Tumkur Road
Kannur on Thanisandra Main Road
Doddanekundi
Kengeri
Horamavu
Thanisandra
Ramamurthy Nagar
Whitefield Hope Farm Junction
Electronic City Phase 1
Yelahanka
Anjanapura
Jalahalli
Kasavanahalli
Whitefield Hope Farm Junction
Bommasandra
Bellandur
RR Nagar
Whitefield Hope Farm Junction
Begur
JP Nagar Phase 1
Dasarahalli on Tumkur Road
Kannur on Thanisandra Main Road
Doddanekundi
Kengeri
Horamavu
Thanisandra
Ramamurthy Nagar
Whitefield Hope Farm Junction
Electronic City Phase 1
Yelahanka
Anjanapura
Jalahalli
Kasavanahalli
Whitefield Hope Farm Junction
Bommasandra
Bellandur
RR Nagar
Whitefield Hope Farm Junction
Begur
Bommasandra
Kannur on Thanisandra Main Road

Hennur
Hennur
Hennur
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Yelahanka
Harlur
Harlur
Junnasandra
Junnasandra
Junnasandra
Junnasandra
Junnasandra
Junnasandra
Junnasandra
Junnasandra
Richmond Town
Kumaraswamy Layout
Dasarahalli on Tumkur Road
Battarahalli
K C Krishna Reddy Layout
Krishnarajapura
Koramangala
Koramangala
Banashankari
Banashankari
Kumaraswamy Layout
Kumaraswamy Layout
Thanisandra
Thanisandra
Kumaraswamy Layout
Kumaraswamy Layout
Hennur
Carmelaram
Carmelaram
Carmelaram
Carmelaram
Varthur
Varthur
Varthur
Varthur
Banashankari
JP Nagar Phase 7
Kumaraswamy Layout
Kumaraswamy Layout
Bommanahalli
Bommanahalli
Electronic City Phase 2
Electronic City Phase 2
RR Nagar
RR Nagar
Konanakunte
Adugodi
Adugodi
Harlur
Harlur
Jakkur
Jakkur
Yelahanka
Yelahanka
Hennur
Kogilu
Kogilu
Kogilu
Krishnarajapura
Krishnarajapura
Krishnarajapura


Kaggadasapura
RR Nagar
RR Nagar
RR Nagar
Kannur on Thanisandra Main Road
Koppa Begur Road
Babusabpalya
Chikkalasandra
Poornaprajna Layout
Banashankari 5th stage
Bharath Housing Society Layout
Electronic City Phase 1
DrVishnuvardhan Road
Hebbal
Hebbal
JP Nagar Phase 7
Yelahanka
BTM Layout
Yelahanka
Uttarahalli Hobli
Talaghattapura
Jayanagar
Jayanagar
Rajajinagar
Hebbal
Basavanagudi
Jayanagar
Uttarahalli
Rajajinagar
Rajajinagar
Rajajinagar
Thanisandra
Basavanagudi
Uttarahalli
Basavanagudi
Rajajinagar
Rajajinagar
Hebbal
Rajajinagar
Rajajinagar
Hebbal
Thanisandra
Thanisandra
Uttarahalli
Devanahalli
AECS Layout A Block Singasandra
Sarjapur Road Wipro To Railway Crossing
Rajarajeshwari nagar
AECS Layout A Block Singasandra
Cooke Town
Yelahanka
KR Puram Bhattarahalli
Raja Rajeshwari Nagar 5th Stage
Raja Rajeshwari Nagar 5th Stage
Jakkur
Poorna Pragna Layout
Poorna Pragna Layout
Poorna Pragna Layout
Raja Rajeshwari Nagar 5th Stage
Poorna Pragna Layout
Poorna Pragna Layout
Electronic City Phase

Kogilu
Hebbal
Kogilu
Kogilu
Bommasandra
Kodihalli on Old Airport Road
Devanahalli
Bellandur
Bilekahalli
Hulimavu
Banashankari
Kudlu Gate
Bagaluru Near Yelahanka
Bellandur
Sarjapur Attibele
Electronic City Phase 2
Banashankari
Chandapura
JP Nagar Phase 2
Hosa Road Electronic City
Bommasandra
Bannerghatta
Uttarahalli
Bellari Road
Kudlu Gate
Bellandur
Sahakar Nagar
Whitefield Hope Farm Junction
Thanisandra
Hosa Road Electronic City
Kudlu Gate
Hosa Road Junction
Doddaballapur
Bhoopasandra
Marathahalli
Narayanapura on Hennur Main Road
Narayanapura on Hennur Main Road
Kachanayakanahalli
Mysore Road
Kumbalgodu
Bilekahalli
Seegehalli Road
Chandapura
Sarjapur Attibele
Channasandra Layout
Ramamurthy Nagar
Chandapura Anekal Road
Chandapura
Budigere
Bagaluru Near Yelahanka
Sarjapur Road
HAL
Bommasandra
Chandapura
Kasavanahalli
Kasavanahalli
Kasavanahalli
Kasavanahalli


In [24]:
location_stats = Bengalore.groupby("Location")["Location"].agg("count")
location_stats

Location
5th Phase                          11
5th Stage BEML Layout               4
5th Stage Raja Rajeshwari Nagar     5
6th phase jp nagar                  1
7th Phase JP Nagar                  1
                                   ..
Yelahanka New Town                  1
Yerthiganahalli                     1
Yeshwantpur                        51
hebbal kempapura                    1
sarjapura attibele road            72
Name: Location, Length: 302, dtype: int64

In [25]:
location_stats_less_than_50 = location_stats[location_stats<=50]
location_stats_less_than_50

Location
5th Phase                          11
5th Stage BEML Layout               4
5th Stage Raja Rajeshwari Nagar     5
6th phase jp nagar                  1
7th Phase JP Nagar                  1
                                   ..
Whitefield                         10
Whitefield Road                     1
Yelahanka New Town                  1
Yerthiganahalli                     1
hebbal kempapura                    1
Name: Location, Length: 265, dtype: int64

In [26]:
Bengalore.Location = Bengalore.Location.apply(lambda x: "other" if x in location_stats_less_than_50 else x)

In [27]:
Bengalore.Location.value_counts()

other                                      2439
Electronic City Phase 2                     232
RR Nagar                                    217
Begur                                       186
Varthur                                     168
Kumaraswamy Layout                          154
Attibele                                    151
Narayanapura on Hennur Main Road            148
Electronic City Phase 1                     139
Harlur                                      135
Krishnarajapura                             131
Yelahanka                                   130
Bommasandra                                 114
Bellandur                                   107
Talaghattapura                              106
Kasavanahalli                               101
Horamavu                                    100
Whitefield Hope Farm Junction                97
Anekal City                                  95
Sarjapur                                     88
ITPL                                    

In [28]:
len(Bengalore.Location.unique())

38

In [29]:
#Now we have to change categorical data to numercial data
dummies = pd.get_dummies(Bengalore.Location)
dummies.head()

Anekal City  Attibele  Avalahalli Off Sarjapur Road  Banashankari  Begur  \
0            0         0                             0             0      0   
1            0         0                             0             0      0   
2            0         0                             0             0      0   
3            0         0                             0             0      0   
4            0         0                             0             0      0   

   Bellandur  Bommasandra  Budigere Cross  Devanahalli  \
0          0            0               0            0   
1          0            0               0            0   
2          0            0               0            0   
3          0            0               0            0   
4          0            0               0            0   

   Electronic City Phase 1  ...  Sarjapur Road Wipro To Railway Crossing  \
0                        0  ...                                        0   
1                        0  ...                                        0   
2                        0  ...                                        0   
3                        0  ...                                        0   
4                        0  ...                                        0   

   Talaghattapura  Uttarahalli  Uttarahalli Main Road  Varthur  \
0               0            0                      0        0   
1               0            0                      0        0   
2               0            0                      0        0   
3               0            0                      0        0   
4               0            0                      0        0   

   Whitefield Hope Farm Junction  Yelahanka  Yeshwantpur  other  \
0                              0          0            0      1   
1                              0          0            0      1   
2                              0          0            0      0   
3                              0          0            0      1   
4                              0          0            0      1   

   sarjapura attibele road  
0                        0  
1                        0  
2                        0  
3                        0  
4                        0  

[5 rows x 38 columns]

In [30]:
Bengalore = pd.concat([Bengalore.drop("Location",axis = "columns"),dummies.drop("other",axis="columns")],axis="columns")

In [31]:
Bengalore.head()

Price  Area  No. of Bedrooms  Anekal City  Attibele  \
0  30000000  3340                4            0         0   
1   7888000  1045                2            0         0   
2   4866000  1179                2            0         0   
3   8358000  1675                3            0         0   
4   6845000  1670                3            0         0   

   Avalahalli Off Sarjapur Road  Banashankari  Begur  Bellandur  Bommasandra  \
0                             0             0      0          0            0   
1                             0             0      0          0            0   
2                             0             0      0          0            0   
3                             0             0      0          0            0   
4                             0             0      0          0            0   

   ...  Sarjapur  Sarjapur Road Wipro To Railway Crossing  Talaghattapura  \
0  ...         0                                        0               0   
1  ...         0                                        0               0   
2  ...         0                                        0               0   
3  ...         0                                        0               0   
4  ...         0                                        0               0   

   Uttarahalli  Uttarahalli Main Road  Varthur  Whitefield Hope Farm Junction  \
0            0                      0        0                              0   
1            0                      0        0                              0   
2            0                      0        0                              0   
3            0                      0        0                              0   
4            0                      0        0                              0   

   Yelahanka  Yeshwantpur  sarjapura attibele road  
0          0            0                        0  
1          0            0                        0  
2          0            0                        0  
3          0            0                        0  
4          0            0                        0  

[5 rows x 40 columns]

In [33]:
Bengalore_X = Bengalore.drop("Price",axis="columns")
Bengalore_X.head()

Area  No. of Bedrooms  Anekal City  Attibele  Avalahalli Off Sarjapur Road  \
0  3340                4            0         0                             0   
1  1045                2            0         0                             0   
2  1179                2            0         0                             0   
3  1675                3            0         0                             0   
4  1670                3            0         0                             0   

   Banashankari  Begur  Bellandur  Bommasandra  Budigere Cross  ...  Sarjapur  \
0             0      0          0            0               0  ...         0   
1             0      0          0            0               0  ...         0   
2             0      0          0            0               0  ...         0   
3             0      0          0            0               0  ...         0   
4             0      0          0            0               0  ...         0   

   Sarjapur Road Wipro To Railway Crossing  Talaghattapura  Uttarahalli  \
0                                        0               0            0   
1                                        0               0            0   
2                                        0               0            0   
3                                        0               0            0   
4                                        0               0            0   

   Uttarahalli Main Road  Varthur  Whitefield Hope Farm Junction  Yelahanka  \
0                      0        0                              0          0   
1                      0        0                              0          0   
2                      0        0                              0          0   
3                      0        0                              0          0   
4                      0        0                              0          0   

   Yeshwantpur  sarjapura attibele road  
0            0                        0  
1            0                        0  
2            0                        0  
3            0                        0  
4            0                        0  

[5 rows x 39 columns]

In [34]:
Bengalore_Y = Bengalore.Price
Bengalore_Y.head()

0    30000000
1     7888000
2     4866000
3     8358000
4     6845000
Name: Price, dtype: int64

# Building the model now


In [36]:
x_train, x_test , y_train , y_test = train_test_split(Bengalore_X,Bengalore_Y,test_size = 0.2,random_state = 10)

In [37]:
Cv = ShuffleSplit( n_splits=5,test_size=.2,random_state=1)

cross_val_score(LinearRegression(),Bengalore_X, Bengalore_Y , cv = Cv)

array([0.2091496 , 0.3546509 , 0.08266309, 0.21958821, 0.14949269])

In [38]:
def find_best_model_using_gridsearchcv(X , y):
    algos = {
        "linear_regression" : {
            "model": LinearRegression() , 
            "params" :{
                "normalize" : [True , False]
            }
    } , 
    "lasso" : {
        "model": Lasso(),
        "params":{
            "alpha":[1,2],
            "selection" : [ "random","cyclic"]
        }
    } ,
        
    "decision_tree":{
        "model": DecisionTreeRegressor(),
        "params" : {
            "criterion": ["mse","friedman_mse"],
            "splitter" : ["best","random"]
            }
        }    
    }
    
    scores=[]
    cv = ShuffleSplit(n_splits=10, test_size=0.2,random_state=0)
    for algo_name , config in algos.items():
        gs = GridSearchCV(config["model"] , config["params"] , cv = Cv , return_train_score=False )
        gs.fit(X , y)
        scores.append({
            "model" : algo_name,
            "best_score":gs.best_score_ , 
            "best_params": gs.best_params_
        })
        
        print("model" , algo_name,"best_score",gs.best_score_ , "best_params" , gs.best_params_)

    return pd.DataFrame(scores , columns=["model" , "best_score" , " best_params"])

In [39]:
find_best_model_using_gridsearchcv(x_train , y_train)

model linear_regression best_score 0.19237420982930414 best_params {'normalize': False}
model lasso best_score 0.19237460021325792 best_params {'alpha': 2, 'selection': 'random'}
model decision_tree best_score -0.2258287486638492 best_params {'criterion': 'friedman_mse', 'splitter': 'best'}


model  best_score   best_params
0  linear_regression    0.192374           NaN
1              lasso    0.192375           NaN
2      decision_tree   -0.225829           NaN

In [40]:
model = Lasso(alpha = 2 , selection="random")

In [41]:
model.fit(x_train , y_train)

Lasso(alpha=2, selection='random')

In [32]:
def predict_price(location, area , bhk):
    loc_index= np.where(kolkata_X.columns==location)[0][0]
    
    print(loc_index)
    x = np.zeros(len(kolkata_X.columns))
    x[0] = area
    x[1] = bhk
    if loc_index >= 0:
        x[loc_index] = 1
        
    return model.predict([x])[0]

In [33]:
kolkata_X.columns

Index(['Area', 'No. of Bedrooms', 'Alipore', 'Ballygunge', 'Bansdroni',
       'Barisha Purba Para Road', 'Behala', 'Dum Dum', 'Garia', 'Howrah',
       'Kasba', 'Keshtopur', 'Konnagar', 'Madhyamgram', 'Madurdaha Hussainpur',
       'Mukundapur', 'Narendrapur', 'Nayabad', 'New Alipore', 'New Town',
       'Rajarhat', 'Salt Lake City', 'Sodepur', 'Sonarpur', 'Tangra',
       'Tiljala', 'Tollygunge', 'Uttarpara Kotrung'],
      dtype='object')

In [34]:
kolkata_X.head(3)

Area  No. of Bedrooms  Alipore  Ballygunge  Bansdroni  \
0  1016                3        0           0          0   
1  1111                2        0           0          0   
2  1020                2        0           0          0   

   Barisha Purba Para Road  Behala  Dum Dum  Garia  Howrah  ...  New Alipore  \
0                        0       0        0      0       0  ...            0   
1                        0       0        0      0       0  ...            0   
2                        0       0        0      0       0  ...            0   

   New Town  Rajarhat  Salt Lake City  Sodepur  Sonarpur  Tangra  Tiljala  \
0         0         0               0        0         0       0        0   
1         0         0               0        0         0       0        0   
2         0         1               0        0         0       0        0   

   Tollygunge  Uttarpara Kotrung  
0           0                  0  
1           0                  0  
2           0                  0  

[3 rows x 28 columns]

In [42]:
type(y_test)

pandas.core.series.Series

In [43]:
y_pred = model.predict(x_test)
y_pred = np.array([y_pred])
y_pred.ndim

2

In [44]:
import json
columns = {
    "data_columns": [col.title() for col in Bengalore_X.columns]
}
with open("Bengalore_columns.json","w") as f:
    f.write(json.dumps(columns))

In [40]:
y_test = np.array([y_test])

y_test.ndim

2

In [41]:
model.coef_

array([ 2.77251239e+03, -1.16641676e+06,  1.88122878e+07, -3.20782357e+06,
       -3.43006587e+06,  9.81741892e+05, -1.14786716e+06, -6.10495309e+05,
       -1.71243053e+06,  1.00814388e+05,  6.64323990e+05, -3.33959583e+06,
       -1.13904088e+06,  2.97253925e+04,  2.14030538e+06,  4.34027741e+06,
       -6.23292703e+05, -9.91743473e+05, -2.06246287e+06, -1.02913263e+06,
       -1.14820432e+06, -7.53464509e+05, -1.41691253e+06, -1.52421517e+06,
       -5.20304271e+05, -1.35296136e+06,  2.14888294e+06, -3.32408860e+05])

In [42]:
model.intercept_

7908410.210968339

In [43]:
#predict_price("loc",area,bhk)
predict_price('Ballygunge',1500,2)

3


6526521.714725935

##### Save The Model

In [45]:
import joblib

In [46]:
with open('Bengalore_model_joblib','wb') as file:
    joblib.dump(model,file)

In [47]:
with open('Bengalore_model_joblib','rb') as file:
    mp = joblib.load(file)

In [48]:
def predict_price(location, area , bhk):
    loc_index= Bengalore.index(location)
    
    x = np.zeros(28)
    x[0] = area
    x[1] = bhk
    if loc_index >= 0:
        x[loc_index] = 1
        
    return mp.predict([x])[0]

In [49]:
np.where(kolkata_X.columns == "Alipore")

(array([2], dtype=int64),)

In [50]:
np.where(kolkata_X.columns == "Alipore")[0]

array([2], dtype=int64)

In [51]:
np.where(kolkata_X.columns == "Alipore")[0][0]

2

In [52]:
predict_price("Alipore" , 2000 , 3)

TypeError: 'RangeIndex' object is not callable

In [ ]:
Length = len(kolkata_X.columns)

In [ ]:
Length

In [53]:
mp.coef_

array([ 2.77251239e+03, -1.16641676e+06,  1.88122878e+07, -3.20782357e+06,
       -3.43006587e+06,  9.81741892e+05, -1.14786716e+06, -6.10495309e+05,
       -1.71243053e+06,  1.00814388e+05,  6.64323990e+05, -3.33959583e+06,
       -1.13904088e+06,  2.97253925e+04,  2.14030538e+06,  4.34027741e+06,
       -6.23292703e+05, -9.91743473e+05, -2.06246287e+06, -1.02913263e+06,
       -1.14820432e+06, -7.53464509e+05, -1.41691253e+06, -1.52421517e+06,
       -5.20304271e+05, -1.35296136e+06,  2.14888294e+06, -3.32408860e+05])

In [54]:
mp.intercept_

7908410.210968339