In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from sklearn.model_selection import train_test_split,cross_val_score , ShuffleSplit , GridSearchCV
from sklearn.linear_model import LinearRegression , Lasso
from sklearn.tree import DecisionTreeRegressor

In [2]:
kolkata= pd.read_csv("kolkata.csv")
kolkata.head(3)

Price  Area   Location  No. of Bedrooms  Resale  MaintenanceStaff  \
0  2235000  1016    Barasat                3       0                 0   
1  3665999  1111  Keshtopur                2       0                 1   
2  3774000  1020   Rajarhat                2       0                 0   

   Gymnasium  SwimmingPool  LandscapedGardens  JoggingTrack  ...  \
0          1             1                  1             1  ...   
1          1             0                  1             1  ...   
2          1             0                  0             0  ...   

   LiftAvailable  BED  VaastuCompliant  Microwave  GolfCourse  TV  \
0              1    0                0          0           0   0   
1              0    0                0          0           0   0   
2              1    0                0          0           0   0   

   DiningTable  Sofa  Wardrobe  Refrigerator  
0            0     0         0             0  
1            0     0         0             0  
2            0     0         0             0  

[3 rows x 40 columns]

In [3]:
kolkata.columns

Index(['Price', 'Area', 'Location', 'No. of Bedrooms', 'Resale',
       'MaintenanceStaff', 'Gymnasium', 'SwimmingPool', 'LandscapedGardens',
       'JoggingTrack', 'RainWaterHarvesting', 'IndoorGames', 'ShoppingMall',
       'Intercom', 'SportsFacility', 'ATM', 'ClubHouse', 'School',
       '24X7Security', 'PowerBackup', 'CarParking', 'StaffQuarter',
       'Cafeteria', 'MultipurposeRoom', 'Hospital', 'WashingMachine',
       'Gasconnection', 'AC', 'Wifi', 'Children'splayarea', 'LiftAvailable',
       'BED', 'VaastuCompliant', 'Microwave', 'GolfCourse', 'TV',
       'DiningTable', 'Sofa', 'Wardrobe', 'Refrigerator'],
      dtype='object')

In [4]:
kolkata.drop(columns=['Resale','MaintenanceStaff', 'Gymnasium', 'SwimmingPool', 'LandscapedGardens',
       'JoggingTrack', 'RainWaterHarvesting', 'IndoorGames', 'ShoppingMall',
       'Intercom', 'SportsFacility', 'ATM', 'ClubHouse', 'School',
       '24X7Security', 'PowerBackup', 'CarParking', 'StaffQuarter',
       'Cafeteria', 'MultipurposeRoom', 'Hospital', 'WashingMachine',
       'Gasconnection', 'AC', 'Wifi', "Children'splayarea", 'LiftAvailable','BED', 
        'VaastuCompliant', 'Microwave', 'GolfCourse', 'TV','DiningTable', 
        'Sofa', 'Wardrobe', 'Refrigerator'],inplace = True)

In [5]:
kolkata.head()

Price  Area     Location  No. of Bedrooms
0  2235000  1016      Barasat                3
1  3665999  1111    Keshtopur                2
2  3774000  1020     Rajarhat                2
3  2524000   935  Narendrapur                2
4  8300000  1956     New Town                3

In [6]:
for col in kolkata.columns:
    print(f'{col}  :- {kolkata[col].unique()}')

Price  :- [  2235000   3665999   3774000 ...   6328000 135000000   4208000]
Area  :- [1016 1111 1020 ... 1002 1369  968]
Location  :- ['Barasat' 'Keshtopur' 'Rajarhat' 'Narendrapur' 'New Town' 'Joka' 'Tangra'
 'Sonarpur' 'Madhyamgram' 'Dum Dum' 'Chkravarti Para' 'Tollygunge'
 'Sarsuna' 'Ultadanga' 'Madurdaha Hussainpur' 'New Alipore' 'Mukundapur'
 'Kutighat' 'Behala' 'Sodepur' 'Konnagar' 'Uttarpara Kotrung' 'Baguiati'
 'Hooghly Chinsurah' 'Hussainpur' 'Dum Dum Park' 'Bhadreswar' 'Garia'
 'south dum dum' 'Santoshpur' 'Gariahat' 'Lake Gardens' 'Kalighat'
 'Belghoria' 'Tagore Park' 'Kamardanga' 'Ballygunge' 'Purba Putiary'
 'Ariadaha' 'Rahara' 'Kasba' 'Paschim Putiary' 'Howrah'
 'Barisha Purba Para Road' 'Tiljala' 'Airport' 'East Kolkata Township'
 'raghunathpur' 'Barrackpore' 'Lake Town' 'Bhawanipur' 'Alipore'
 'Park Street Area' 'Elgin' 'Thakurpukur' 'Ashok Nagar' 'Haltu'
 'Salt Lake City' 'Kaikhali' 'Chinar Park' 'Baranagar' 'Chandannagar'
 'Garfa' 'Jorabagan' 'Baidyabati' 'Topsia' 'Dh

In [7]:
kolkata.dtypes

Price               int64
Area                int64
Location           object
No. of Bedrooms     int64
dtype: object

In [8]:
kolkata["No. of Bedrooms"].unique()

array([3, 2, 4, 1, 5, 6, 9], dtype=int64)

In [9]:
kolkata["No. of Bedrooms"].value_counts()

3    3128
2    2622
4     512
1     198
5      38
6       8
9       1
Name: No. of Bedrooms, dtype: int64

In [10]:
for index , i in enumerate(kolkata["No. of Bedrooms"]):
    if i==9:
        print(index)

3746


In [11]:
kolkata.head()

Price  Area     Location  No. of Bedrooms
0  2235000  1016      Barasat                3
1  3665999  1111    Keshtopur                2
2  3774000  1020     Rajarhat                2
3  2524000   935  Narendrapur                2
4  8300000  1956     New Town                3

In [12]:
kolkata["Location"].unique()

array(['Barasat', 'Keshtopur', 'Rajarhat', 'Narendrapur', 'New Town',
       'Joka', 'Tangra', 'Sonarpur', 'Madhyamgram', 'Dum Dum',
       'Chkravarti Para', 'Tollygunge', 'Sarsuna', 'Ultadanga',
       'Madurdaha Hussainpur', 'New Alipore', 'Mukundapur', 'Kutighat',
       'Behala', 'Sodepur', 'Konnagar', 'Uttarpara Kotrung', 'Baguiati',
       'Hooghly Chinsurah', 'Hussainpur', 'Dum Dum Park', 'Bhadreswar',
       'Garia', 'south dum dum', 'Santoshpur', 'Gariahat', 'Lake Gardens',
       'Kalighat', 'Belghoria', 'Tagore Park', 'Kamardanga', 'Ballygunge',
       'Purba Putiary', 'Ariadaha', 'Rahara', 'Kasba', 'Paschim Putiary',
       'Howrah', 'Barisha Purba Para Road', 'Tiljala', 'Airport',
       'East Kolkata Township', 'raghunathpur', 'Barrackpore',
       'Lake Town', 'Bhawanipur', 'Alipore', 'Park Street Area', 'Elgin',
       'Thakurpukur', 'Ashok Nagar', 'Haltu', 'Salt Lake City',
       'Kaikhali', 'Chinar Park', 'Baranagar', 'Chandannagar', 'Garfa',
       'Jorabagan', 'Ba

In [13]:
len(kolkata["Location"].unique())

308

In [14]:
(kolkata["Location"].value_counts())

New Town                 711
Rajarhat                 405
Tangra                   369
Dum Dum                  316
Garia                    307
                        ... 
Baguiati Hela Battala      1
Mohisbathan                1
Keyatala                   1
Bally                      1
Pratapaditya Road          1
Name: Location, Length: 308, dtype: int64

In [15]:
for i in kolkata["Location"]:
    print(i)

Barasat
Keshtopur
Rajarhat
Narendrapur
New Town
Joka
Tangra
Sonarpur
Sonarpur
Madhyamgram
Dum Dum
New Town
New Town
Chkravarti Para
Tollygunge
Sarsuna
Ultadanga
Madurdaha Hussainpur
New Alipore
Mukundapur
Barasat
Keshtopur
Rajarhat
Narendrapur
New Town
Joka
Tangra
Sonarpur
Sonarpur
Madhyamgram
Dum Dum
New Town
New Town
Chkravarti Para
Tollygunge
Sarsuna
Ultadanga
Madurdaha Hussainpur
New Alipore
Mukundapur
Kutighat
New Town
New Town
Dum Dum
Behala
Sodepur
Konnagar
Uttarpara Kotrung
Baguiati
Hooghly Chinsurah
New Town
Hussainpur
Dum Dum Park
Barasat
New Town
Rajarhat
Dum Dum
Bhadreswar
Dum Dum
Dum Dum
New Town
Garia
New Town
south dum dum
Rajarhat
Santoshpur
Behala
Rajarhat
Gariahat
Uttarpara Kotrung
Lake Gardens
Rajarhat
Rajarhat
New Town
New Town
Kalighat
Garia
Belghoria
Garia
Tangra
Tagore Park
Kamardanga
New Town
Rajarhat
Mukundapur
Tollygunge
Mukundapur
Ballygunge
Keshtopur
Purba Putiary
New Town
Ariadaha
Garia
Rahara
Behala
Kasba
New Town
New Town
New Town
Sodepur
Paschim Putiary


New Town
Barisha
Barisha Purba Para Road
Barisha Purba Para Road
Dakshineswar
Maheshtala
Maheshtala
Behala
Bansdroni
Bansdroni
New Town
Uttarpara Kotrung
Kamarhati on BT Road
Uttarpara Kotrung
Uttarpara Kotrung
Uttarpara Kotrung
Jodhpur Park
Jodhpur Park
Bansdroni
Rajarhat
Keshtopur
Keshtopur
Narendrapur
Narendrapur
Narendrapur
Narendrapur
Narendrapur
Narendrapur
Ichapur
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
New Town
New Town
Narendrapur
Narendrapur
Narendrapur
Narendrapur
Narendrapur
Narendrapur
Ichapur
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Behala
Behala
Salkia
Bally
Barisha Purba Para Road
Barisha Purba Para Road
Behala
Keshtopur
Barisha Purba Para Road
Barisha Purba Para Road
Tiljala
Tagore Park
Tagore Park
Barisha Purba Para Road
Barisha Purba Para Road
Behala
Keshtopur
Barisha Purba Para Road
Barisha Purba Para 

Tangra
Tangra
Tangra
Tangra
Tangra
Tangra
Tangra
Nayabad
Lake Gardens
Tollygunge
Keshtopur
Tangra
Tangra
Tollygunge
Lake Gardens
Paschim Putiary
Garia
Barisha Purba Para Road
Behala
Tiljala
Tiljala
Haltu
Haltu
Baranagar
Tollygunge
Bansdroni
Tollygunge
Tollygunge
Haltu
Paschim Putiary
Garia
Tollygunge
Chandannagar
Chandannagar
Tollygunge
Chandannagar
Chandannagar
Chandannagar
Barasat
Barasat
Barasat
Chandannagar
Haltu
Paschim Putiary
Paschim Putiary
Paschim Putiary
Ward No 113
Tollygunge
Nayabad
Sodepur
Netaji Nagar
Tollygunge
Tangra
Tollygunge
Chandannagar
Noapara
Hussainpur
Tollygunge
Tollygunge
Chandannagar
Keshtopur
Kankurgachi
Tangra
Noapara
Keshtopur
Barasat
Barasat
Barasat
Haltu
Kamardanga
Garia
Tollygunge
Tollygunge
Jodhpur Park
Lake Gardens
Tollygunge
Tollygunge
Sodepur
Lake Gardens
Keshtopur
Tiljala
Tollygunge
Tollygunge
Sinthi
Haltu
Kankurgachi
Netaji Nagar
Hussainpur
Hussainpur
Rajarhat
Garia
Garia
Dum Dum
Garia
Garia
Garia
Paschim Putiary
Tollygunge
New Town
Bramhapur
Tagor

Kankurgachi
Tangra
Nayabad
Rajarhat
Rajarhat
Rajarhat
Rajarhat
Rajarhat
Rajarhat
Rajarhat
Kasba
Rajarhat
New Alipore
Joka
Keshtopur
Rajarhat
Sonarpur
Topsia
B T Road
Nazir Bagan
Konnagar
Rajarhat
New Town
New Town
Dum Dum Metro
Kasba
Kaikhali
E M Bypass
Dhakuria
Eastend Park Kalikapur
New Town
Konnagar
Rajarhat
birati
Konnagar
NSC Bose Road Mahamaya Tala Garia
New Town
Uttarpara Kotrung
Tangra
Narendrapur
Narendrapur
Chatterjee Bagan
Tangra
Tangra
Kamalgazi Flyover
EM Bypass South East
Garia
Garia
Sodepur B T Road
Topsia
E M Bypass
E M Bypass
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Mukundapur
Topsia
Topsia
Alipore
Alipore
Alipore
Alipore
Alipore
Alipore
Chingrighata
Keshtopur
Belghoria
Jorabagan
Patuli
Tangra
Tangra
Garia
Howrah
Rajarhat
Rajarhat
Picnic Garden
Rajpur
Madurdaha
Sulekha
Dhakuria
Prince Anwar Shah Connector
Tangra
Bramhapur
Naktala
Kasba


Kaikhali
Rajarhat
Kaikhali
New Town
New Town
New Town
Howrah
Tangra
New Town
Dum Dum
Rajarhat
New Town
Lake Town
Rajarhat
Lake Town
New Town
New Town
Madurdaha Hussainpur
Belghoria
Narendrapur
N S C Bose Road  Narendrapur
Narendrapur
New Town
Rajarhat
shalimar
Lake Gardens
E M Bypass
Santoshpur
Howrah
Howrah
Madhyamgram
birati
Behala Chowrasta
birati
Biren Roy Road
Bramhapur
Dum Dum
Narendrapur
Madhyamgram
Howrah
New Town
Uttarpara Kotrung
Narendrapur
N S C Bose Road Narendrapur
Rajarhat
Howrah
Tollygunge
BADU ROAD
Dum Dum
Dum Dum
Narendrapur
Narendrapur
Rajpur
Narendrapur
New Town
Prince Anwar Shah Connector
Ultadanga
Alipore
Tangra
Tangra
Dum Dum Park
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Dum Dum
Howrah
Dum Dum
Dum Dum
Howrah
Bangur
Kalitala Road
Bansdroni
Bansdroni
New Town
New Town
Belghoria Expressway
Rajarhat
Rajarhat
Behala
International Airport
Rajarhat
New Town
New Town
New Alipore
Narendrapur
Narendrapur
N S C Bose Road Narendrapur
kalikapur
Konnagar
N S C Bose Road  Narend

In [16]:
location_stats = kolkata.groupby("Location")["Location"].agg("count")
location_stats

Location
Acharya Jagadish Chandra Bose Road     1
Action Area I                          2
Action Area I Newtown                  8
Action Area II Newtown                 2
Action Area IIB Newtown                1
                                      ..
purbalok                               2
raghunathpur                           2
salt lake sec iii                      3
shalimar                               4
south dum dum                         14
Name: Location, Length: 308, dtype: int64

In [17]:
location_stats_less_than_50 = location_stats[location_stats<=50]
location_stats_less_than_50

Location
Acharya Jagadish Chandra Bose Road     1
Action Area I                          2
Action Area I Newtown                  8
Action Area II Newtown                 2
Action Area IIB Newtown                1
                                      ..
purbalok                               2
raghunathpur                           2
salt lake sec iii                      3
shalimar                               4
south dum dum                         14
Name: Location, Length: 282, dtype: int64

In [18]:
kolkata.Location = kolkata.Location.apply(lambda x: "other" if x in location_stats_less_than_50 else x)

In [19]:
kolkata.Location.value_counts()

other                      1830
New Town                    711
Rajarhat                    405
Tangra                      369
Dum Dum                     316
Garia                       307
Howrah                      276
Behala                      232
Tollygunge                  201
Madhyamgram                 200
Narendrapur                 190
Keshtopur                   182
Alipore                     176
Sonarpur                    141
Mukundapur                  123
Sodepur                      98
Kasba                        93
New Alipore                  87
Salt Lake City               81
Tiljala                      78
Bansdroni                    64
Nayabad                      64
Barisha Purba Para Road      63
Uttarpara Kotrung            58
Ballygunge                   55
Konnagar                     55
Madurdaha Hussainpur         52
Name: Location, dtype: int64

In [20]:
len(kolkata.Location.unique())

27

In [21]:
#Now we have to change categorical data to numercial data
dummies = pd.get_dummies(kolkata.Location)
dummies.head()

Alipore  Ballygunge  Bansdroni  Barisha Purba Para Road  Behala  Dum Dum  \
0        0           0          0                        0       0        0   
1        0           0          0                        0       0        0   
2        0           0          0                        0       0        0   
3        0           0          0                        0       0        0   
4        0           0          0                        0       0        0   

   Garia  Howrah  Kasba  Keshtopur  ...  New Town  Rajarhat  Salt Lake City  \
0      0       0      0          0  ...         0         0               0   
1      0       0      0          1  ...         0         0               0   
2      0       0      0          0  ...         0         1               0   
3      0       0      0          0  ...         0         0               0   
4      0       0      0          0  ...         1         0               0   

   Sodepur  Sonarpur  Tangra  Tiljala  Tollygunge  Uttarpara Kotrung  other  
0        0         0       0        0           0                  0      1  
1        0         0       0        0           0                  0      0  
2        0         0       0        0           0                  0      0  
3        0         0       0        0           0                  0      0  
4        0         0       0        0           0                  0      0  

[5 rows x 27 columns]

In [22]:
kolkata = pd.concat([kolkata.drop("Location",axis = "columns"),dummies.drop("other",axis="columns")],axis="columns")

In [23]:
kolkata.head()

Price  Area  No. of Bedrooms  Alipore  Ballygunge  Bansdroni  \
0  2235000  1016                3        0           0          0   
1  3665999  1111                2        0           0          0   
2  3774000  1020                2        0           0          0   
3  2524000   935                2        0           0          0   
4  8300000  1956                3        0           0          0   

   Barisha Purba Para Road  Behala  Dum Dum  Garia  ...  New Alipore  \
0                        0       0        0      0  ...            0   
1                        0       0        0      0  ...            0   
2                        0       0        0      0  ...            0   
3                        0       0        0      0  ...            0   
4                        0       0        0      0  ...            0   

   New Town  Rajarhat  Salt Lake City  Sodepur  Sonarpur  Tangra  Tiljala  \
0         0         0               0        0         0       0        0   
1         0         0               0        0         0       0        0   
2         0         1               0        0         0       0        0   
3         0         0               0        0         0       0        0   
4         1         0               0        0         0       0        0   

   Tollygunge  Uttarpara Kotrung  
0           0                  0  
1           0                  0  
2           0                  0  
3           0                  0  
4           0                  0  

[5 rows x 29 columns]

In [24]:
kolkata_X = kolkata.drop("Price",axis="columns")
kolkata_X.head()

Area  No. of Bedrooms  Alipore  Ballygunge  Bansdroni  \
0  1016                3        0           0          0   
1  1111                2        0           0          0   
2  1020                2        0           0          0   
3   935                2        0           0          0   
4  1956                3        0           0          0   

   Barisha Purba Para Road  Behala  Dum Dum  Garia  Howrah  ...  New Alipore  \
0                        0       0        0      0       0  ...            0   
1                        0       0        0      0       0  ...            0   
2                        0       0        0      0       0  ...            0   
3                        0       0        0      0       0  ...            0   
4                        0       0        0      0       0  ...            0   

   New Town  Rajarhat  Salt Lake City  Sodepur  Sonarpur  Tangra  Tiljala  \
0         0         0               0        0         0       0        0   
1         0         0               0        0         0       0        0   
2         0         1               0        0         0       0        0   
3         0         0               0        0         0       0        0   
4         1         0               0        0         0       0        0   

   Tollygunge  Uttarpara Kotrung  
0           0                  0  
1           0                  0  
2           0                  0  
3           0                  0  
4           0                  0  

[5 rows x 28 columns]

In [25]:
kolkata_Y = kolkata.Price
kolkata_Y.head()

0    2235000
1    3665999
2    3774000
3    2524000
4    8300000
Name: Price, dtype: int64

# Building the model now


In [26]:
x_train, x_test , y_train , y_test = train_test_split(kolkata_X,kolkata_Y,test_size = 0.2,random_state = 10)

In [27]:
Cv = ShuffleSplit( n_splits=5,test_size=.2,random_state=1)

cross_val_score(LinearRegression(),kolkata_X, kolkata_Y , cv = Cv)

array([0.13259667, 0.09616962, 0.0908593 , 0.15875273, 0.09454676])

In [28]:
def find_best_model_using_gridsearchcv(X , y):
    algos = {
        "linear_regression" : {
            "model": LinearRegression() , 
            "params" :{
                "normalize" : [True , False]
            }
    } , 
    "lasso" : {
        "model": Lasso(),
        "params":{
            "alpha":[1,2],
            "selection" : [ "random","cyclic"]
        }
    } ,
        
    "decision_tree":{
        "model": DecisionTreeRegressor(),
        "params" : {
            "criterion": ["mse","friedman_mse"],
            "splitter" : ["best","random"]
            }
        }    
    }
    
    scores=[]
    cv = ShuffleSplit(n_splits=10, test_size=0.2,random_state=0)
    for algo_name , config in algos.items():
        gs = GridSearchCV(config["model"] , config["params"] , cv = Cv , return_train_score=False )
        gs.fit(X , y)
        scores.append({
            "model" : algo_name,
            "best_score":gs.best_score_ , 
            "best_params": gs.best_params_
        })
        
        print("model" , algo_name,"best_score",gs.best_score_ , "best_params" , gs.best_params_)

    return pd.DataFrame(scores , columns=["model" , "best_score" , " best_params"])

In [29]:
find_best_model_using_gridsearchcv(x_train , y_train)

model linear_regression best_score 0.07589593107713706 best_params {'normalize': False}
model lasso best_score 0.07589628872340992 best_params {'alpha': 2, 'selection': 'cyclic'}
model decision_tree best_score -0.24537030064181672 best_params {'criterion': 'friedman_mse', 'splitter': 'random'}


model  best_score   best_params
0  linear_regression    0.075896           NaN
1              lasso    0.075896           NaN
2      decision_tree   -0.245370           NaN

In [30]:
model = Lasso(alpha = 2 , selection="cyclic")

In [31]:
model.fit(x_train , y_train)

Lasso(alpha=2)

In [32]:
def predict_price(location, area , bhk):
    loc_index= np.where(kolkata_X.columns==location)[0][0]
    
    print(loc_index)
    x = np.zeros(len(kolkata_X.columns))
    x[0] = area
    x[1] = bhk
    if loc_index >= 0:
        x[loc_index] = 1
        
    return model.predict([x])[0]

In [33]:
kolkata_X.columns

Index(['Area', 'No. of Bedrooms', 'Alipore', 'Ballygunge', 'Bansdroni',
       'Barisha Purba Para Road', 'Behala', 'Dum Dum', 'Garia', 'Howrah',
       'Kasba', 'Keshtopur', 'Konnagar', 'Madhyamgram', 'Madurdaha Hussainpur',
       'Mukundapur', 'Narendrapur', 'Nayabad', 'New Alipore', 'New Town',
       'Rajarhat', 'Salt Lake City', 'Sodepur', 'Sonarpur', 'Tangra',
       'Tiljala', 'Tollygunge', 'Uttarpara Kotrung'],
      dtype='object')

In [34]:
kolkata_X.head(3)

Area  No. of Bedrooms  Alipore  Ballygunge  Bansdroni  \
0  1016                3        0           0          0   
1  1111                2        0           0          0   
2  1020                2        0           0          0   

   Barisha Purba Para Road  Behala  Dum Dum  Garia  Howrah  ...  New Alipore  \
0                        0       0        0      0       0  ...            0   
1                        0       0        0      0       0  ...            0   
2                        0       0        0      0       0  ...            0   

   New Town  Rajarhat  Salt Lake City  Sodepur  Sonarpur  Tangra  Tiljala  \
0         0         0               0        0         0       0        0   
1         0         0               0        0         0       0        0   
2         0         1               0        0         0       0        0   

   Tollygunge  Uttarpara Kotrung  
0           0                  0  
1           0                  0  
2           0                  0  

[3 rows x 28 columns]

In [35]:
predict_price('Sodepur' , 1100 , 2 )

22


7208427.791638204

In [36]:
kolkata_Y.head(3)

0    2235000
1    3665999
2    3774000
Name: Price, dtype: int64

In [37]:
type(y_test)

pandas.core.series.Series

In [38]:
y_pred = model.predict(x_test)
y_pred = np.array([y_pred])
y_pred.ndim

2

In [39]:
import json
columns = {
    "data_columns": [col.title() for col in kolkata_X.columns]
}
with open("Kolkata_columns.json","w") as f:
    f.write(json.dumps(columns))

In [40]:
y_test = np.array([y_test])

y_test.ndim

2

In [41]:
model.coef_

array([ 2.77251239e+03, -1.16641676e+06,  1.88122878e+07, -3.20782357e+06,
       -3.43006587e+06,  9.81741892e+05, -1.14786716e+06, -6.10495309e+05,
       -1.71243053e+06,  1.00814388e+05,  6.64323990e+05, -3.33959583e+06,
       -1.13904088e+06,  2.97253925e+04,  2.14030538e+06,  4.34027741e+06,
       -6.23292703e+05, -9.91743473e+05, -2.06246287e+06, -1.02913263e+06,
       -1.14820432e+06, -7.53464509e+05, -1.41691253e+06, -1.52421517e+06,
       -5.20304271e+05, -1.35296136e+06,  2.14888294e+06, -3.32408860e+05])

In [42]:
model.intercept_

7908410.210968339

In [43]:
#predict_price("loc",area,bhk)
predict_price('Ballygunge',1500,2)

3


6526521.714725935

##### Save The Model

In [44]:
import joblib

In [45]:
with open('Kolkata_model_joblib','wb') as file:
    joblib.dump(model,file)

In [47]:
with open('Kolkata_model_joblib','rb') as file:
    mp = joblib.load(file)

In [48]:
def predict_price(location, area , bhk):
    loc_index= kolkata.index(location)
    
    x = np.zeros(28)
    x[0] = area
    x[1] = bhk
    if loc_index >= 0:
        x[loc_index] = 1
        
    return mp.predict([x])[0]

In [49]:
np.where(kolkata_X.columns == "Alipore")

(array([2], dtype=int64),)

In [50]:
np.where(kolkata_X.columns == "Alipore")[0]

array([2], dtype=int64)

In [51]:
np.where(kolkata_X.columns == "Alipore")[0][0]

2

In [52]:
predict_price("Alipore" , 2000 , 3)

TypeError: 'RangeIndex' object is not callable

In [ ]:
Length = len(kolkata_X.columns)

In [ ]:
Length

In [53]:
mp.coef_

array([ 2.77251239e+03, -1.16641676e+06,  1.88122878e+07, -3.20782357e+06,
       -3.43006587e+06,  9.81741892e+05, -1.14786716e+06, -6.10495309e+05,
       -1.71243053e+06,  1.00814388e+05,  6.64323990e+05, -3.33959583e+06,
       -1.13904088e+06,  2.97253925e+04,  2.14030538e+06,  4.34027741e+06,
       -6.23292703e+05, -9.91743473e+05, -2.06246287e+06, -1.02913263e+06,
       -1.14820432e+06, -7.53464509e+05, -1.41691253e+06, -1.52421517e+06,
       -5.20304271e+05, -1.35296136e+06,  2.14888294e+06, -3.32408860e+05])

In [54]:
mp.intercept_

7908410.210968339